<?php
// No direct access to this file
defined('_JEXEC') or die('Restricted access');

// import Joomla controllerform library
jimport('joomla.application.component.controllerform');

/**
 * Booking Controller
 */
class BookaTableControllerBooking extends JControllerForm
{

    protected function allowSave($data, $key = 'id')
    {
        $recordId = isset($data[$key]) ? $data[$key] : '0';

        //comprovació d'overbooking
        /** @var JDatabaseDriver $db */
        $db = JFactory::getDbo();
        $query = $db->getQuery(true);

        $query->select('*')
            ->from('#__bookatable_bookings')
            ->where('date = "' . $data['date'] .'"')
            ->where('table_id = ' . $data['table_id'])
            ->where('evening = ' . $data['evening']);

        if($recordId > 0){
            $query->where('id =' . $recordId);
        }

        $db->setQuery($query);

        $db->execute();

        if (count($db->loadObjectList()) > 0) {
            return false;
        }

        //comprovació una reserva activa per usuari
        if($recordId == 0) {

            $query = $db->getQuery(true);

            $query->select('*')
                ->from('#__bookatable_bookings')
                ->where('id != ' . $recordId)
                ->where('date >= CURDATE()')
                ->where('user_id = ' . $data['user_id']);

            $db->setQuery($query);

            $db->execute();

            if (count($db->loadObjectList()) > 0) {
                return false;
            }

        }

        return parent::allowSave($data, $key); // TODO: Change the autogenerated stub
    }
}
